spring.datasource.url=jdbc:postgresql://mahmud.db.elephantsql.com:5432/kwqbsfiu
spring.datasource.username=kwqbsfiu
spring.datasource.password=HQY8USTko0CG_Q-1vxJyrI6jt36sPvBJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect
